version: "3.3"
services:
  redis:
    image: redis:latest
  webapp:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - nginx-vol:/usr/share/nginx/html
    networks:
      - nginx-net
    links:
      - redis
    ports:
      - "80:80"
volumes:
  nginx-vol:
networks:
  nginx-net: